### ISSUE TITLE
Is there a way to restore the keyboard?

### ISSUE THREAD

**Issue by axd1x8a** [castleberrysam/byk870-fw#2]
After launching the wrong executable, I got an endless message waiting and code version 3011. I have a motospeed ck104 on a byk870 chip, is there a way to restore it?

**Comment by axd1x8a** [comment]
![IMG_20210416_041156_761](https://user-images.githubusercontent.com/26704473/114957852-84670c80-9e6a-11eb-9650-200d2b930405.jpg)

**Comment by axd1x8a** [comment]
@castleberrysam, do you know how to fix it?

**Comment by castleberrysam** [comment]
Yes, I emailed someone in the past who had the same problem, he was able to fix this by opening the case and shorting two of the microcontroller pins together.

**Comment by castleberrysam** [comment]
![how to reset](https://user-images.githubusercontent.com/4407610/115082431-844b2900-9ecb-11eb-8fad-97aa72699bf8.png)
![Pins](https://user-images.githubusercontent.com/4407610/115082438-8614ec80-9ecb-11eb-84b4-8720965e61f9.png)

**Comment by castleberrysam** [comment]
You should be able to identify the orientation of the chip by the round mark as shown in the second image.

**Comment by axd1x8a** [comment]
yes, I already tried this, but it didn't help in my case

**Comment by FeeeeK** [comment]
https://user-images.githubusercontent.com/26704473/115086745-889c3400-9f15-11eb-8ba2-a0b07834b75a.mp4

**Comment by FeeeeK** [comment]
this is how it works now

**Comment by castleberrysam** [comment]
From the emails:

> At first, I tested the first firmware, this is where the BYK800 is written.
The keyboard was flashed but became inoperative. Then I decided to flash
the second firmware that should have been suitable. It was the firmware
BYK870 RGB. After that, the keyboard came to life and began to work
correctly. It became interesting to me, I decided to flash the third
firmware, after that the keyboard again became inoperative, and the native
firmware did not help. When I started the native flash driver, I received
the code 3011 and the repeated keyboard reconnections in Windows 10. If you
close the flash driver, the keyboard lights up red but is incomplete and
does not work, the keys are confused, some of them do not work at all.

> I also started looking for datasheets on the original chip and I found it. I
will attach it with a PDF file to the letter. This file describes the
process of resetting the chip by closing certain contacts. Well, I started
trying. I launched the desired flasher of those three, connected the
disassembled keyboard to the PC, closed the necessary contacts and the
keyboard was identified as an input device in the system. The firmware
passed and the keyboard worked.

Can you try to do it again in exactly the way that he describes?

**Comment by axd1x8a** [comment]
No, it didn't help, but I found two reasons for this
1. second pin is not GND
2. 
![изображение_2021-04-17_011638](https://user-images.githubusercontent.com/26704473/115089263-8f797580-9f1a-11eb-918a-621d05ee43dc.png)
![image](https://user-images.githubusercontent.com/26704473/115089600-3bbb5c00-9f1b-11eb-8199-c4900731f5e1.png)

**Comment by axd1x8a** [comment]
But to be honest, I don't know what these codes are

**Comment by castleberrysam** [comment]
The second pin is not GND? You mean it does not measure as 0V? If this is the same chip, that's not possible...

**Comment by castleberrysam** [comment]
The original guy also had a motospeed ck104 keyboard, so it seems really likely that you have the same chip.

**Comment by axd1x8a** [comment]
I mean, pin 11 needs to be closed not with 12

**Comment by castleberrysam** [comment]
For the codes, I'm also not sure. It's probably some parameters configurable by the JTAG programmer, which I have done some research on in the past, but we don't have access to it. In any case, I don't believe this pin is used as GPIO or Timer4 output in the code so hopefully it's already configured in the correct mode for RST operation.

**Comment by castleberrysam** [comment]
You should be connecting pins 11 and 12 together (but maybe that's what you mean).

**Comment by axd1x8a** [comment]
And the pdf that he sent is in the repository?  I just couldn't find anything about pin closure there.

**Comment by castleberrysam** [comment]
Yeah it's the same pdf. This is what refers to the pin closure: "The device will be reset by a low voltage on this pin longer than 10us."

**Comment by axd1x8a** [comment]
There is no way to do it using the program?

**Comment by castleberrysam** [comment]
The program is what has stopped working correctly in this case, so the hardware reset acts as a backup. I'm unable to give you any other advice since I don't have access to the device to look at it.

**Comment by castleberrysam** [comment]
I believe that you have the same issue as the other guy, though, so it should somehow be possible for you to recover the device as he did.
